const API_URL = localStorage.getItem("AMB_API_URL") || "https://script.google.com/macros/s/AKfycbxLFaIE7KyT5PsIGiWeZYiPE_RBEJrP7W-SZqL8A318V-e3WtbYrkhXcjMr8HIetZUG/exec";
let reports=[], crews=["Rehan","Driver 2","Driver 3"], selectedPhoto=null;
const $=id=>document.getElementById(id);
const money=n=>"Rp "+Number(n||0).toLocaleString("id-ID");
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const isoToday=()=>{let d=new Date(); return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
function go(page){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$("page-"+page).classList.add("active");document.querySelectorAll(".nav-btn").forEach(x=>x.classList.toggle("active",x.dataset.page===page));if(page==="dashboard")refreshDashboard();if(page==="rekap")loadReports();if(page==="custom")renderCustom();}
function toggleNav(){document.querySelector("#mainNav").classList.toggle("open")}
document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>{go(b.dataset.page);document.querySelector("#mainNav").classList.remove("open")});
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2800)}
function setDayName(){let d=$("date").value;if(d){let dt=new Date(d+"T12:00:00");$("dayName").value=dt.toLocaleDateString("id-ID",{weekday:"long"})}}
function formatInputMoney(el){let v=el.value.replace(/\D/g,"");el.value=v?Number(v).toLocaleString("id-ID"):""}
["cashIn","cashOut"].forEach(id=>$(id).addEventListener("input",e=>formatInputMoney(e.target)));
$("date").addEventListener("change",setDayName);
$("photo").addEventListener("change",async e=>{selectedPhoto=null;const f=e.target.files[0];if(!f)return;const data=await resizeImage(f,1200,.72);selectedPhoto={name:f.name,mime:"image/jpeg",data};$("photoPreview").innerHTML=`<img src="${data}" alt="preview">`});
function resizeImage(file,max,quality){return new Promise((resolve,reject)=>{let im=new Image(),r=new FileReader();r.onload=()=>{im.onload=()=>{let s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext("2d").drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL("image/jpeg",quality))};im.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
async function api(action,payload={}){if(API_URL.includes("PASTE_")){toast("Hubungkan API Google Apps Script di app.js dulu.");throw new Error("API belum disetel")};let r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,...payload})});let j=await r.json();if(!j.ok)throw new Error(j.error||"Gagal");return j}
async function loadInitial(){let today=isoToday();$("date").value=today;$("dashDate").value=today;$("filterFrom").value=today;$("filterTo").value=today;setDayName();try{let j=await api("bootstrap");crews=j.crews||crews;renderCrew();reports=j.reports||[];refreshDashboard()}catch(e){renderCrew();$("dashStatus").textContent="Mode lokal / API belum tersambung"}}
function renderCrew(){$("crew").innerHTML=crews.map(x=>`<option>${esc(x)}</option>`).join("")}
function refreshDashboard(){let d=$("dashDate").value||isoToday();let rs=reports.filter(r=>r.date===d);$("statPatients").textContent=rs.length;$("statIn").textContent=money(rs.reduce((a,r)=>a+num(r.cashIn),0));$("statOut").textContent=money(rs.reduce((a,r)=>a+num(r.cashOut),0));$("statBalance").textContent=money(rs.reduce((a,r)=>a+num(r.cashIn)-num(r.cashOut),0));$("statKm").textContent=rs.reduce((a,r)=>a+num(r.km),0).toLocaleString("id-ID")+" km";$("dashStatus").textContent=rs.length+" laporan";$("todayList").innerHTML=rs.length?rs.map(reportMini).join(""):`<div class="muted">Belum ada laporan untuk tanggal ini.</div>`}
function reportMini(r){return `<div class="report-item"><div><b>${esc(r.patient)}</b><small>${esc(r.purpose)}</small></div><div>🕐 ${esc(r.time)}<br><small>${esc(r.crew)} • ${esc(r.vehicle)}</small></div><div>💰 ${money(r.cashIn)}<br>🛣️ ${num(r.km)} km</div><div><button class="action" onclick="showDetail('${esc(r.id)}')">Detail</button></div></div>`}
function changeDay(n){let d=new Date(($("dashDate").value||isoToday())+"T12:00:00");d.setDate(d.getDate()+n);$("dashDate").value=d.toISOString().slice(0,10);refreshDashboard()}
function num(v){return Number(String(v??0).replace(/[^\d.-]/g,""))||0}
function payloadFromForm(){return {id:$("reportId").value||crypto.randomUUID(),day:$("dayName").value,date:$("date").value,time:$("time").value,purpose:$("purpose").value,patient:$("patient").value,address:$("address").value,pickup:$("pickup").value,destination:$("destination").value,vehicle:$("vehicle").value,crew:$("crew").value,cashIn:num($("cashIn").value),cashOut:num($("cashOut").value),cashOutNote:$("cashOutNote").value,note:$("note").value,km:0}}
$("reportForm").addEventListener("submit",async e=>{e.preventDefault();let p=payloadFromForm();if(p.cashOut>0&&!p.cashOutNote.trim()){toast("Keterangan kas keluar wajib diisi.");$("cashOutNote").focus();return}try{toast("Menyimpan…");let j=await api("save",{report:p,photo:selectedPhoto});p.photoUrl=j.photoUrl||"";p.photoId=j.photoId||"";let i=reports.findIndex(x=>x.id===p.id);if(i>=0)reports[i]=p;else reports.push(p);toast("Laporan tersimpan.");resetForm(false);go("dashboard")}catch(e){toast(e.message)}});
function resetForm(clear=true){$("reportForm").reset();$("reportId").value="";$("date").value=isoToday();$("time").value=new Date().toTimeString().slice(0,5);setDayName();$("photoPreview").innerHTML="";selectedPhoto=null;if(clear)toast("Form dibersihkan")}
function openMaps(id){let q=$(id).value.trim();if(!q){toast("Isi lokasi dulu.");return}window.open("https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(q),"_blank")}
function openRoute(){let a=$("pickup").value.trim(),b=$("destination").value.trim();if(!a||!b){toast("Isi titik jemput dan tujuan dulu.");return}window.open("https://www.google.com/maps/dir/?api=1&origin="+encodeURIComponent(a)+"&destination="+encodeURIComponent(b)," _blank")}
async function duplicateYesterday(){let d=new Date(($("date").value||isoToday())+"T12:00:00");d.setDate(d.getDate()-1);let ds=d.toISOString().slice(0,10),r=reports.filter(x=>x.date===ds).sort((a,b)=>a.time.localeCompare(b.time))[0];if(!r){toast("Belum ada laporan kemarin.");return}["purpose","patient","address","pickup","destination","vehicle","crew","cashOutNote","note"].forEach(k=>{if($(k))$(k).value=r[k]||""});$("date").value=isoToday();$("time").value=r.time||"08:00";$("cashIn").value=r.cashIn?Number(r.cashIn).toLocaleString("id-ID"):"";$("cashOut").value=r.cashOut?Number(r.cashOut).toLocaleString("id-ID"):"";setDayName();toast("Data kemarin disalin. Silakan cek dan simpan sebagai laporan baru.")}
async function loadReports(){let f=$("filterFrom").value,t=$("filterTo").value,s=$("filterSearch").value.toLowerCase();let rs=reports.filter(r=>(!f||r.date>=f)&&(!t||r.date<=t)&&(!s||JSON.stringify(r).toLowerCase().includes(s)));$("reportTable").innerHTML=rs.sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)).map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.time)}</td><td>${esc(r.patient)}</td><td>${esc(r.purpose)}</td><td>${esc(r.crew)}</td><td>${esc(r.vehicle)}</td><td>${money(r.cashIn)} / ${money(r.cashOut)}</td><td>${num(r.km)}</td><td><button class="action" onclick="showDetail('${esc(r.id)}')">Detail</button> <button class="action" onclick="copyWhatsApp('${esc(r.id)}')">WA</button></td></tr>`).join("")||`<tr><td colspan="9" class="muted">Tidak ada data.</td></tr>`}
function getReport(id){return reports.find(r=>r.id===id)}
function wa(r){return `*Laporan Layanan AmbulanMu Godean*\\n\\n*Hari* : *${r.day||""}*\\n\\n*Tanggal* : *${r.date}*\\n\\n*Waktu* : *${r.time}wib*\\n\\n*Keperluan* : *${r.purpose}*\\n\\n*Nama* : *${r.patient}*\\n\\n*Alamat* : *${r.address||"-"}*\\n\\n*Titik jemput* : *${r.pickup}*\\n\\n*Titik Tujuan* : *${r.destination}*\\n\\n*Armada* : *${r.vehicle}*\\n\\n*Crew* : *${r.crew}*\\n\\n*Kas Masuk* : *${money(r.cashIn)}*\\n\\n*Kas keluar* : *${money(r.cashOut)}*\\n\\n*Ket.Kas keluar* : *${r.cashOutNote||"-"}*\\n\\n*Note* : *${r.note||"-"}*\\n\\n*Jarak layanan* : *${num(r.km)} km*\\n\\n*Tetap semangat melayani umat*,\\n*Memberi untuk Negeri*`}
async function copyWhatsApp(id){let r=getReport(id);await navigator.clipboard.writeText(wa(r));toast("Format WhatsApp disalin.");}
async function copyAllWhatsApp(){let f=$("filterFrom").value,t=$("filterTo").value;let rs=reports.filter(r=>(!f||r.date>=f)&&(!t||r.date<=t)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));if(!rs.length){toast("Tidak ada data untuk disalin.");return}await navigator.clipboard.writeText(rs.map(wa).join("\\n\\n--------------------\\n\\n"));toast("Semua laporan disalin ke clipboard.");}
function exportCSV(){let f=$("filterFrom").value,t=$("filterTo").value,rs=reports.filter(r=>(!f||r.date>=f)&&(!t||r.date<=t));let headers=["Tanggal","Hari","Waktu","Keperluan","Nama","Alamat","Titik Jemput","Titik Tujuan","Armada","Crew","Kas Masuk","Kas Keluar","Ket. Kas Keluar","Note","KM","Foto"];let rows=rs.map(r=>[r.date,r.day,r.time,r.purpose,r.patient,r.address,r.pickup,r.destination,r.vehicle,r.crew,r.cashIn,r.cashOut,r.cashOutNote,r.note,r.km,r.photoUrl]);let csv=[headers,...rows].map(row=>row.map(x=>`"${String(x??"").replaceAll('"','""')}"`).join(",")).join("\\r\\n");let blob=new Blob(["\\ufeff"+csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="rekap-ambulancemu-godean.csv";a.click();URL.revokeObjectURL(a.href)}
function showDetail(id){let r=getReport(id);if(!r)return;let maps=`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(r.pickup)}&destination=${encodeURIComponent(r.destination)}`;let photo=r.photoUrl?`<p><b>Dokumentasi</b></p><img src="${esc(r.photoUrl)}" style="max-width:100%;border-radius:14px;cursor:pointer" onclick="window.open('${esc(r.photoUrl)}','_blank')" alt="Dokumentasi layanan">`:"<p class='muted'>Tidak ada foto.</p>";$("modalContent").innerHTML=`<h2>${esc(r.patient)} — ${esc(r.purpose)}</h2><div class="detail-grid">${Object.entries({Tanggal:r.date,Waktu:r.time,Alamat:r.address||"-","Titik Jemput":r.pickup,"Titik Tujuan":r.destination,Armada:r.vehicle,Crew:r.crew,"Kas Masuk":money(r.cashIn),"Kas Keluar":money(r.cashOut),"Ket. Kas Keluar":r.cashOutNote||"-",Note:r.note||"-",Jarak:num(r.km)+" km"}).map(([k,v])=>`<div class="detail-row"><b>${esc(k)}</b>${esc(v)}</div>`).join("")}</div><p><a href="${maps}" target="_blank" rel="noopener">🗺️ Buka rute di Google Maps</a></p>${photo}<div class="form-footer"><button class="secondary" onclick="copyWhatsApp('${esc(r.id)}')">📋 Salin WhatsApp</button></div>`;$("modal").classList.add("show")}
function hideModal(){$("modal").classList.remove("show")}function closeModal(e){if(e.target.id==="modal")hideModal()}
function renderCustom(){let order=JSON.parse(localStorage.getItem("navOrder")||'["dashboard","input","rekap","custom"]'),labels={dashboard:"Dashboard",input:"Isi Laporan",rekap:"Rekap Data",custom:"Custom"};$("navOrder").innerHTML=order.map((x,i)=>`<div class="order-row"><span>${labels[x]}</span><span><button onclick="moveNav(${i},-1)">↑</button> <button onclick="moveNav(${i},1)">↓</button></span></div>`).join("");let p=JSON.parse(localStorage.getItem("prefs")||"{}");document.querySelectorAll("[data-pref]").forEach(x=>x.checked=p[x.dataset.pref]!==false);applyPrefs()}
function moveNav(i,d){let o=JSON.parse(localStorage.getItem("navOrder")||'["dashboard","input","rekap","custom"]'),j=i+d;if(j<0||j>=o.length)return;[o[i],o[j]]=[o[j],o[i]];localStorage.setItem("navOrder",JSON.stringify(o));renderCustom()}
function saveNavOrder(){let o=JSON.parse(localStorage.getItem("navOrder")||'["dashboard","input","rekap","custom"]');let nav=document.querySelector("#mainNav");o.forEach(x=>{let b=document.querySelector(`.nav-btn[data-page="${x}"]`);if(b)nav.appendChild(b)});toast("Tata letak menu tersimpan di perangkat ini.")}
function savePrefs(){let p={};document.querySelectorAll("[data-pref]").forEach(x=>p[x.dataset.pref]=x.checked);localStorage.setItem("prefs",JSON.stringify(p));applyPrefs();toast("Preferensi tersimpan.")}
function applyPrefs(){let p=JSON.parse(localStorage.getItem("prefs")||"{}");document.querySelector(".hero").style.display=p.hero===false?"none":"";document.querySelector(".stats-grid").style.display=p.stats===false?"none":"";document.querySelector("#todayList").parentElement.style.display=p.daily===false?"none":""}
async function boot(){renderCustom();saveNavOrder();resetForm(false);loadInitial()}
boot();
